<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-KIBHVTP" failures="1" tests="4" name="Test" time="47.307" errors="0" timestamp="2023-03-02T17:55:35 IST">
  <testcase classname="tms.mb.admin.CreatePackageTest" name="createPackageTest" time="19.537"/>
  <testcase classname="tms.mb.admin.AdminCreatePackage_UpdateSamePackageTest" name="adminCreatePackage_UpdateSamePackageTest" time="18.372"/>
  <testcase classname="tms.mb.user.CancelPackageAfterBookingTest" name="cancelPackageAfterBookingTest" time="26.404"/>
  <testcase classname="tms.mb.user.ConfirmPackageAfterBookingTest" name="confirmPackageAfterBookingTest" time="31.829">
    <failure type="java.lang.AssertionError" message="Canceled by admin at 2023-03-02 04:23:40 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Canceled by admin at 2023-03-02 04:23:40 expected [true] but found [false]
at tms.mb.user.ConfirmPackageAfterBookingTest.confirmPackageAfterBookingTest(ConfirmPackageAfterBookingTest.java:74)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- confirmPackageAfterBookingTest -->
</testsuite> <!-- Test -->
